version: '3.7'

services:
  web:
    build: ./
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000


# version: '2'

# services:
#   web:
#     build: ./
#     command: python /code/manage.py runserver 0.0.0.0:8000
#     volumes:
#       - .:/code
#     ports:
#       - "8000:8000"
#   # documentation:
#   #   restart: always
#   #   build: ./
#   #   command: "mkdocs serve"
#   #   volumes:
#   #     - ./:/code
#   #   ports:
#   #     - "8001:8001"
# volumes:
#   my-datavolume:
